# Generated by Django 2.1.7 on 2020-10-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField()),
                ('abstractID', models.IntegerField()),
                ('autherID', models.IntegerField()),
            ],
        ),
    ]
